DROP TABLE IF EXISTS message;
DROP TABLE IF EXISTS portal;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE portal (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  name text NOT NULL
);

CREATE TABLE message (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  content text NOT NULL,
  author text NOT NULL,
  create_timestamp TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE message
  ADD COLUMN portal_id uuid REFERENCES portal(id) ON DELETE CASCADE NOT NULL;